/* 
 * WebApp
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UserInfoViewModel
    /// </summary>
    [DataContract]
    public partial class UserInfoViewModel :  IEquatable<UserInfoViewModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserInfoViewModel" /> class.
        /// </summary>
        /// <param name="Email">Email.</param>
        /// <param name="HasRegistered">HasRegistered.</param>
        /// <param name="LoginProvider">LoginProvider.</param>
        public UserInfoViewModel(string Email = null, bool? HasRegistered = null, string LoginProvider = null)
        {
            this.Email = Email;
            this.HasRegistered = HasRegistered;
            this.LoginProvider = LoginProvider;
        }
        
        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name="Email", EmitDefaultValue=false)]
        public string Email { get; set; }
        /// <summary>
        /// Gets or Sets HasRegistered
        /// </summary>
        [DataMember(Name="HasRegistered", EmitDefaultValue=false)]
        public bool? HasRegistered { get; set; }
        /// <summary>
        /// Gets or Sets LoginProvider
        /// </summary>
        [DataMember(Name="LoginProvider", EmitDefaultValue=false)]
        public string LoginProvider { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserInfoViewModel {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  HasRegistered: ").Append(HasRegistered).Append("\n");
            sb.Append("  LoginProvider: ").Append(LoginProvider).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UserInfoViewModel);
        }

        /// <summary>
        /// Returns true if UserInfoViewModel instances are equal
        /// </summary>
        /// <param name="other">Instance of UserInfoViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserInfoViewModel other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Email == other.Email ||
                    this.Email != null &&
                    this.Email.Equals(other.Email)
                ) && 
                (
                    this.HasRegistered == other.HasRegistered ||
                    this.HasRegistered != null &&
                    this.HasRegistered.Equals(other.HasRegistered)
                ) && 
                (
                    this.LoginProvider == other.LoginProvider ||
                    this.LoginProvider != null &&
                    this.LoginProvider.Equals(other.LoginProvider)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Email != null)
                    hash = hash * 59 + this.Email.GetHashCode();
                if (this.HasRegistered != null)
                    hash = hash * 59 + this.HasRegistered.GetHashCode();
                if (this.LoginProvider != null)
                    hash = hash * 59 + this.LoginProvider.GetHashCode();
                return hash;
            }
        }
    }

}
