/* 
 * WebApp
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ToDoItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ToDoItemTests
    {
        // TODO uncomment below to declare an instance variable for ToDoItem
        //private ToDoItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ToDoItem
            //instance = new ToDoItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ToDoItem
        /// </summary>
        [Test]
        public void ToDoItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ToDoItem
            //Assert.IsInstanceOfType<ToDoItem> (instance, "variable 'instance' is a ToDoItem");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'IsCompleted'
        /// </summary>
        [Test]
        public void IsCompletedTest()
        {
            // TODO unit test for the property 'IsCompleted'
        }
        /// <summary>
        /// Test the property 'IsNotify'
        /// </summary>
        [Test]
        public void IsNotifyTest()
        {
            // TODO unit test for the property 'IsNotify'
        }
        /// <summary>
        /// Test the property 'NextNotifyTime'
        /// </summary>
        [Test]
        public void NextNotifyTimeTest()
        {
            // TODO unit test for the property 'NextNotifyTime'
        }
        /// <summary>
        /// Test the property 'ToDoList'
        /// </summary>
        [Test]
        public void ToDoListTest()
        {
            // TODO unit test for the property 'ToDoList'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ToDoListId'
        /// </summary>
        [Test]
        public void ToDoListIdTest()
        {
            // TODO unit test for the property 'ToDoListId'
        }

    }

}
