/* 
 * WebApp
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserInfoViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserInfoViewModelTests
    {
        // TODO uncomment below to declare an instance variable for UserInfoViewModel
        //private UserInfoViewModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserInfoViewModel
            //instance = new UserInfoViewModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserInfoViewModel
        /// </summary>
        [Test]
        public void UserInfoViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserInfoViewModel
            //Assert.IsInstanceOfType<UserInfoViewModel> (instance, "variable 'instance' is a UserInfoViewModel");
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'HasRegistered'
        /// </summary>
        [Test]
        public void HasRegisteredTest()
        {
            // TODO unit test for the property 'HasRegistered'
        }
        /// <summary>
        /// Test the property 'LoginProvider'
        /// </summary>
        [Test]
        public void LoginProviderTest()
        {
            // TODO unit test for the property 'LoginProvider'
        }

    }

}
