/* 
 * WebApp
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ToDoItemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ToDoItemApiTests
    {
        private ToDoItemApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ToDoItemApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ToDoItemApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ToDoItemApi
            //Assert.IsInstanceOfType(typeof(ToDoItemApi), instance, "instance is a ToDoItemApi");
        }

        
        /// <summary>
        /// Test ToDoItemGetAll
        /// </summary>
        [Test]
        public void ToDoItemGetAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToDoItemGetAll();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemGetAllNotCompleted
        /// </summary>
        [Test]
        public void ToDoItemGetAllNotCompletedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToDoItemGetAllNotCompleted();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemGetById
        /// </summary>
        [Test]
        public void ToDoItemGetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ToDoItemGetById(id);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemInsertItem
        /// </summary>
        [Test]
        public void ToDoItemInsertItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoItem item = null;
            //var response = instance.ToDoItemInsertItem(item);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemMarkAsCompleted
        /// </summary>
        [Test]
        public void ToDoItemMarkAsCompletedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ToDoItemMarkAsCompleted(id);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemRemoveItem
        /// </summary>
        [Test]
        public void ToDoItemRemoveItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoItem item = null;
            //var response = instance.ToDoItemRemoveItem(item);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoItemUpdateItem
        /// </summary>
        [Test]
        public void ToDoItemUpdateItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoItem item = null;
            //var response = instance.ToDoItemUpdateItem(item);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
